baseURL = "https://www.tropyc.co"
languageCode = "en-us"
title = "Tropyc"
description = "Tropyc - Crypto Community"
Paginate = 3

googleAnalytics = "UA-106154604-1"
disqusShortname = "tropyc"

[Params]
  RSSLink = "/index.xml"
  author = "Tropyc"
  telegram = "Tropyc"
  facebook = "tropyc"
  twitter = "tropyc_crypto"
  email = "hello@tropyc.co"

[[menu.main]]
    name = "News"
    weight = 10
    url = "/news/"
[[menu.main]]
    name = "Crypto 101"
    weight = 20
    url = "/crypto-101/"
[[menu.main]]
    name = "Exchanges"
    weight = 30
    url = "/exchanges/"
[[menu.main]]
    name = "Markets"
    weight = 40
    url = "/markets/"
[[menu.main]]
    name = "Token sales"
    weight = 50
    url = "/token-sales/"
