baseURL = "https://tropyc.netlify.com"
languageCode = "en-us"
title = "Tropyc"
theme = "kube"
description = "Tropyc - Crypto Community"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Tropyc"
  telegram = "Tropyc"
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "News"
    weight = 10
    url = "/news/"
[[menu.main]]
    name = "Crypto 101"
    weight = 20
    url = "/crypto-101/"
[[menu.main]]
    name = "Purchase"
    weight = 30
    url = "/purchase/"
[[menu.main]]
    name = "Tokens"
    weight = 40
    url = "/tokens/"
[[menu.main]]
    name = "Token sales"
    weight = 50
    url = "/token-sales/"
