baseURL = "https://www.tropyc.co"
languageCode = "en-us"
languageLang = "en"
title = "Tropyc"
description = "Crypto news, educational content, token sale(ICO) rating."
Paginate = 3

googleAnalytics = "UA-106154604-1"
disqusShortname = "tropyc"

[Params]
	images = ["images/tropyc/tropyc-open-graph.png"]
  RSSLink = "/index.xml"
  author = "Tropyc"
  telegram = "Tropyc"
  facebook = "tropyc"
  twitter = "tropyc_crypto"
  email = "hello@tropyc.co"

[[menu.main]]
    name = "News"
    weight = 10
    url = "/news/"
[[menu.main]]
    name = "Crypto 101"
    weight = 20
    url = "/crypto-101/"
[[menu.main]]
    name = "ICOs - Token sales"
    weight = 30
    url = "/token-sales/"

[related]

# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 80

# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = false

# Will lower case keywords in both queries and in the indexes.
toLower = false

[[related.indices]]
name = "date"
weight = 150
